### ISSUE TITLE
ИЗменение меню

### ISSUE THREAD

**Issue by DamirCheboksarov** [youdenfive/Snakes#15]
Необходимо убрать ненужный размер поля, так как почти ничего не меняется, убрать ботов из мультиплеера, заменить параметр bots в singleplayer на bot - on или off. Пофиксить отображение всего текста во время игры, поработать над начислением очков за смерть: -5, за убийство бота: +10, а также определять победителя по количеству очков, и в соответствии с этим выводить определенный текст в конце игры

**Comment by youdenfive** [comment]
- Добавить статистику игроков
- Добавить настройки управления для второго игрока
